const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');

const defaultConfig = getDefaultConfig(__dirname);

const config = {
  resolver: {
    alias: {
      '@': './src',
      '@components': './src/components',
      '@services': './src/services',
      '@store': './src/store',
      '@styles': './src/styles',
    },
  },
  transformer: {
    ...defaultConfig.transformer,
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
    minifierPath: require.resolve('metro-minify-terser'),
    minifierConfig: {
      // Suppress warnings about undeclared globals like Promise, console
      ecma: 2017,
      warnings: false,
      parse: {
        ecma: 2017,
      },
      compress: {
        ecma: 2017,
        warnings: false,
        // Promise and console are globals, so don't warn about them
        keep_infinity: true,
        // Suppress warnings about undeclared variables
        drop_console: false,
        pure_funcs: [],
        // Suppress all warnings about undeclared globals
        unsafe: false,
        unsafe_comps: false,
        unsafe_math: false,
        unsafe_proto: false,
        unsafe_regexp: false,
        unsafe_undefined: false,
      },
      // Define globals at the top level to suppress warnings
      global_defs: {
        console: 'console',
        Promise: 'Promise',
        setTimeout: 'setTimeout',
        clearTimeout: 'clearTimeout',
        setInterval: 'setInterval',
        clearInterval: 'clearInterval',
        Date: 'Date',
        JSON: 'JSON',
        Math: 'Math',
        Object: 'Object',
        Array: 'Array',
        String: 'String',
        Number: 'Number',
        Boolean: 'Boolean',
        Error: 'Error',
        RegExp: 'RegExp',
        globalThis: 'globalThis',
        global: 'global',
        window: 'window',
        document: 'document',
        navigator: 'navigator',
        location: 'location',
        process: 'process',
        __dirname: '__dirname',
        __filename: '__filename',
        Buffer: 'Buffer',
        require: 'require',
        module: 'module',
        exports: 'exports',
        fetch: 'fetch',
        XMLHttpRequest: 'XMLHttpRequest',
        WebSocket: 'WebSocket',
        Blob: 'Blob',
        File: 'File',
        FileReader: 'FileReader',
        FormData: 'FormData',
        URL: 'URL',
        URLSearchParams: 'URLSearchParams',
        Headers: 'Headers',
        Request: 'Request',
        Response: 'Response',
        AbortController: 'AbortController',
        AbortSignal: 'AbortSignal',
        MessageChannel: 'MessageChannel',
        MessagePort: 'MessagePort',
        reportError: 'reportError',
        DebuggerInternal: 'DebuggerInternal',
        // React Native / Metro specific globals
        __DEV__: '__DEV__',
        __BUNDLE_START_TIME__: '__BUNDLE_START_TIME__',
        __METRO_GLOBAL_PREFIX__: '__METRO_GLOBAL_PREFIX__',
        __requireCycleIgnorePatterns: '__requireCycleIgnorePatterns',
        __REACT_DEVTOOLS_GLOBAL_HOOK__: '__REACT_DEVTOOLS_GLOBAL_HOOK__',
        nativePerformanceNow: 'nativePerformanceNow',
        nativeLoggingHook: 'nativeLoggingHook',
        nativeCallSyncHook: 'nativeCallSyncHook',
        nativeFlushQueueImmediate: 'nativeFlushQueueImmediate',
        nativeQueueCall: 'nativeQueueCall',
        nativeRuntimeScheduler: 'nativeRuntimeScheduler',
        // Hermes specific
        HermesInternal: 'HermesInternal',
        // Common globals
        Map: 'Map',
        Set: 'Set',
        WeakMap: 'WeakMap',
        WeakSet: 'WeakSet',
        Symbol: 'Symbol',
        Proxy: 'Proxy',
        Reflect: 'Reflect',
        Intl: 'Intl',
        SharedArrayBuffer: 'SharedArrayBuffer',
        Atomics: 'Atomics',
        Int8Array: 'Int8Array',
        Uint8Array: 'Uint8Array',
        Uint8ClampedArray: 'Uint8ClampedArray',
        Int16Array: 'Int16Array',
        Uint16Array: 'Uint16Array',
        Int32Array: 'Int32Array',
        Uint32Array: 'Uint32Array',
        Float32Array: 'Float32Array',
        Float64Array: 'Float64Array',
        DataView: 'DataView',
        TypedArray: 'TypedArray',
      },
      output: {
        ecma: 2017,
        comments: false,
        ascii_only: true,
      },
    },
  },
};

module.exports = mergeConfig(defaultConfig, config);
